PSP/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import admin
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views
from django.conf import settings
from django.conf.urls.static import static


from peoplestory import views



urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r"^AboutUs/$", views.About, name="about"),
    url(r"^ContactUs/$", views.Contact, name="contact"),
    url(r"^PrivacyPolicy/$", views.PrivacyPolicy, name="privacy_policy"),

    path('accounts/', include('accounts.urls')),
    path('Stories/', include('peoplestory.urls')),
    path('DM/', include('directmessages.urls')),
    #authentication urls
    url('^', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.http import HttpResponse
from django.shortcuts import render

from accounts import views

urlpatterns = [
    url(r"^SignUp/$", views.NewRegularUser, name="signup"),
    url(r"^SignUp/Admin/$", views.NewAdminUser, name="admin_signup"),
    url(r"^MyProfile/(?P<pk>\d+)/$", views.MyProfile, name="myprofile"),  
    url(r"^MyProfile/ProfileUpdate/(?P<pk>\d+)$", views.UserProfileUpdateView, name="profile_update"),  
    url(r"^TopAuthors/$", views.TopAuthors, name="top_authors"),
    url(r"^TopAuthor/SearchResult/$", views.AuthorSearchResultView.as_view(), name="author_search_results"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from cloudinary.models import CloudinaryField
from django.utils.text import Truncator
from directmessages.models import Message
from directmessages.middleware import RequestMiddleware
from django.db.models import Q
from django.core.cache import cache
from django.conf import settings
import datetime


MALE = 'Male'
FEMALE = 'Female'
GENDER = [
    (MALE, 'male'),
    (FEMALE, 'female'),
]


class User(AbstractUser):
    is_regular = models.NullBooleanField(default=False, db_index=True)
    is_admin = models.NullBooleanField(default=False, db_index=True)
    email = models.EmailField(max_length=254, blank=True, unique=True)


class UserProfile(models.Model):
    bio = models.TextField(blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    phone_number = models.CharField( max_length=50, blank=True, null=True)
    date_of_birth = models.DateField(auto_now=False, auto_now_add=False)
    nationality = models.CharField( max_length=50, null=True, blank=True)
    profile_pic = models.ImageField(upload_to="profile_pic", null=True, blank=True)
    profile_pic_url = models.CharField(max_length=2000, blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} Profile'

    @property
    def truncated_bio(self):
        truncated_bio = Truncator(self.bio)
        return truncated_bio.chars(60)

    @property
    def unread_messages(self):
        '''to display a list of unread messages that this user recieves'''
        unread_msg = Message.objects.all().filter(recipient=self.user, read_at=None)
        return unread_msg

    @property
    def unread_messages_from_me(self):
        '''to display a list of unread messages that this user recieves'''
        request = RequestMiddleware(get_response=None)
        request = request.thread_local.current_request
        unread_msg_from_me = Message.objects.all().filter(sender=self.user, recipient=request.user, read_at=None)
        return unread_msg_from_me

    @property
    def last_msg_from_user(self):
        '''to display a truncated last message recieved from a particular'''
        request = RequestMiddleware(get_response=None)
        request = request.thread_local.current_request
        last = Message.objects.all().filter(Q(sender=self.user, recipient=request.user) | Q(sender=request.user, recipient=self.user)).last().content
        truncated_last = Truncator(last)
        return truncated_last.chars(30)

    
    def last_seen(self):
        return cache.get('seen_%s' % self.user.pk)

    def online(self):
        if self.last_seen():
            now = datetime.datetime.now()
            if now > self.last_seen() + datetime.timedelta(
                         seconds=settings.USER_ONLINE_TIMEOUT):
                return False
            else:
                return True
        else:
            return False

    def all_online_users(self):
        '''returns a list of all users that are online now'''
        return cache.get('online-now')


    

directmessages/models.py
from __future__ import unicode_literals
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
import datetime
from django.db.models import Q

from django.conf import settings
from django.utils.translation import ugettext_lazy as _

AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')

class ChatRoomManager(models.Manager):

    def get_or_new(self, user1, user2): # get_or_create
        if user1 == user2:
            return None
        qlookup1 = Q(first=user1) & Q(second=user2)
        qlookup2 = Q(first=user2) & Q(second=user1)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user1.__class__
            user = Klass.objects.get(username=user2.username)
            if user1 != user:
                obj = self.model(
                        first=user1, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False

class ChatRoom(models.Model):
    """
    A thread for each message, like a room that contains two folks
    """
    first        = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    timestamp    = models.DateTimeField(default=datetime.datetime.now())

    objects      = ChatRoomManager()

    def __int__(self):
        return self.id


class Message(models.Model):
    """
    A private directmessage
    """
    content = models.TextField(_('Content'))
    sender = models.ForeignKey(AUTH_USER_MODEL, related_name='sent_dm', verbose_name=_("Sender"), on_delete=models.CASCADE)
    recipient = models.ForeignKey(AUTH_USER_MODEL, related_name='received_dm', verbose_name=_("Recipient"), on_delete=models.CASCADE)
    sent_at = models.DateTimeField(_("sent at"), null=True, blank=True)
    read_at = models.DateTimeField(_("read at"), null=True, blank=True)
    room = models.ForeignKey(ChatRoom, null=True, blank=True, on_delete=models.SET_NULL)


    @property
    def unread(self):
        """returns whether the message was read or not"""
        if self.read_at is not None:
            return False
        return True

    def __str__(self):
        return self.content

    def save(self, **kwargs):
        if self.sender == self.recipient:
            raise ValidationError("You can't send messages to yourself")

        if not self.id:
            self.sent_at = datetime.datetime.now()
        super(Message, self).save(**kwargs)  

accounts/forms.py
import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User, UserProfile
from cloudinary.forms import CloudinaryFileField


MALE = 'Male'
FEMALE = 'Female'
GENDER = [
    (MALE, 'male'),
    (FEMALE, 'female'),
]


class RegularUserCreationForm(UserCreationForm):
    first_name = forms.CharField( max_length=30, required=True)
    last_name = forms.CharField( max_length=30, required=True)
    date_of_birth = forms.DateField()
    email = forms.EmailField(max_length = 254, required=False, help_text='enter a valid email address.')
    phone_number = forms.CharField( max_length=30, required=False)
    nationality = forms.CharField( max_length=30, required=True)
    profile_pic = forms.ImageField(required=False)
    x = forms.FloatField(required=False)
    y = forms.FloatField(required=False)
    width = forms.FloatField(required=False)
    height = forms.FloatField(required=False)
    bio = forms.CharField( max_length=2555, required=False)

    class Meta:
        model = User
        User.is_regular = True
        fields = ('username', 'first_name', 'last_name', 'date_of_birth', 'bio', 'email', 
            'phone_number', 'nationality', 'profile_pic', 'x', 'y', 'width', 'height', 'password1', 'password2')



class AdminUserCreationForm(UserCreationForm):
    first_name = forms.CharField( max_length=30, required=False)
    last_name = forms.CharField( max_length=30, required=False)
    date_of_birth = forms.DateField()
    email = forms.EmailField(max_length = 254, required=False, help_text='enter a valid email address.')
    phone_number = forms.CharField( max_length=30, required=False)
    nationality = forms.CharField( max_length=30, required=False)
    profile_pic = forms.ImageField(required=False)
    x = forms.FloatField(required=False)
    y = forms.FloatField(required=False)
    width = forms.FloatField(required=False)
    height = forms.FloatField(required=False)

    class Meta:
        model = User
        User.is_admin = True
        User.is_regular = False
        fields = ('username', 'first_name', 'last_name', 'date_of_birth', 'email', 
            'phone_number', 'nationality', 'profile_pic', 'password1', 'password2')


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')


class UserProfileUpdateForm(forms.ModelForm):
    profile_pic = forms.ImageField(required=False)
    x = forms.FloatField(required=False)
    y = forms.FloatField(required=False)
    width = forms.FloatField(required=False)
    height = forms.FloatField(required=False)
    bio = forms.CharField( max_length=2555, required=False)

    class Meta:
        model = UserProfile
        fields = ('phone_number', 'nationality', 'profile_pic', 'bio', 'x', 'y', 'width', 'height')

accounts/templates/myprofile.html
{% extends 'base.html' %}

{% block headerlinks %}
    <link rel="stylesheet" href="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588534997/static/css/bootstrap.min_sq8nsp.css">
    
{% endblock %}

{% block style %}

body{
    background: white;
}
footer{
    display: none;
}
.profile_section{
    padding-top: 0px;
    margin-top: 100px;
    margin-left: 30px;
    margin-right: 30px;
}
.picture-aside{
    text-align: center;
    background: white;z
}
.profile_pic{
    border-radius: 100%;
    max-width: 70%;
    margin-bottom: 30px;
}
.story_count{
    font-size: -webkit-xxx-large;
}
.story_count_stories{
    font-size: x-large;
    margin-bottom: 0px;
}
.profile_hr{
    margin-top: 0px;
}
.bio_tittle{
    font-weight: 600;
    color: #2f85d9;
}
.stories_title{
    color:#2f85d9;
}
<!--Modal styling-->
.modal-title{
    margin: 0px;
}
 {% endblock %}


{% block content %}

    <section class=" s-content--top-padding s-content--narrow profile_section">
        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-10 picture-aside" >
            
            {% if user.userprofile.profile_pic_url %}
                <img class="profile_pic" src="{{ user.userprofile.profile_pic_url }}" alt="">
            {% else %}
                <img class="profile_pic" src="https://res.cloudinary.com/people-shaping-people/image/upload/v1581157209/Default%20Images/head-659651_1920_tfjm1i.png" alt="">
            {% endif %}
                <p style="color: rgba(0, 0, 0, 0.5);">@{{ user.username }}
                {% if request.user != user %}
                   <a data-toggle="modal" data-target="#Modal" data-whatever="@mdo"> 
                        <i class="fas fa-envelope" style="padding-left:10px;"></i> 
                   </a>
                {% endif %}
                
                {% if user.userprofile.online == True %}
                        <i class="fas fa-circle" style="color: #22f722;font-size: 1rem;"></i><span style="color:">online</span>
                {% else %}
                {% endif %}
                    
                </p>
                
            <h1 class="entry__header-title display-1 " 
                style="margin-bottom: 0px; color: slategrey;">
                    {{ user.first_name }} {{ user.last_name }}
            </h1>
                <ul style="color: rgba(0, 0, 0, 0.5); list-style-type:none; float: left;">
                    <li style="float: left;"><span>
                        <i class="fas fa-map-marker-alt"></i>
                        {{ user.userprofile.nationality }}
                    </span></li>
                    <li style="float: left;"><span>
                        <i class="fas fa-at"></i>
                        {{ user.email }}
                    </span></li>
                    <li style="float: left;"><span>
                        <i class="fas fa-phone"></i>
                        {{ user.userprofile.phone_number }}
                    </span></li>
                </ul>
            {% if user == request.user %}
                <div class="col-12">
                    <a href="{% url 'profile_update' user.pk %}" class=" col-lg-6 col-md-6 col-sm-6 col-xs-8">
                        Edit Profile
                    </a>
                </div>
            {% endif %}
        </div>

        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8 picture-aside">
            <div>
                <span>
                    <img src="https://res.cloudinary.com/people-shaping-people/image/upload/v1588535124/static/images/icons/story_rbapkp.png" alt="icon"/>
                </span>
                <p class="story_count_stories"><span class="story_count">{{ mystory.count }} </span>Stories</p>
                <hr class="profile_hr">    
            </div>
            <div>
                <p>
                    {% if user.userprofile.bio %}
                    <p><span class="bio_tittle">Bio : </span>{{ user.userprofile.bio }}</p>
                        
                    {% endif %}
                </p>
            </div>
            <div style="margin-bottom: 65px;">
                <h2 class="entry__header-title stories_title">Stories</h2>    
                <ul class="list-group">
                    {% for story in mystory %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'story_detail' story.pk %}">{{ story.full_name }}</a>
                            <span class="badge badge-primary badge-pill">{{ story.views }}</span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

    </section> <!-- end s-extra -->

    <!-- CHAT MODAL -->
    <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        
        <div class="modal-body">
            <form>
            <div class="form-group">
                <label for="recipient-name" class="col-form-label" style="padding-left: 0px;font-size: 1.6rem;">
                    Recipient: 
                </label>
                <input type="text" class="form-control" id="recipient-name" value="@{{ user.username }}" disabled
                        style="
                                padding-bottom: 0px;
                                padding-top: 0px;
                                height: 50px;
                                padding-left: 10px;
                            ">
            </div>
            <div class="form-group">
                <form method="Post" class="form" post-href="{% url 'msg_post_url' %}">
					{% csrf_token %}
                    <label for="message-text" class="col-form-label" style="padding-left: 0px;font-size: 1.6rem;">Message:</label>
                    <textarea class="form-control" id="id_content" style="font-size: 1.6rem;"></textarea>
                
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="Submit" class="btn btn-primary btn_submit">Send message</button>
                </form>
        </div>
        </div>
    </div>
    </div>
    <!--end of CHAT MODAL-->

{% endblock content %}

{% block javascript %}

<script>

$('.btn_submit').click(function(e){ 
		e.preventDefault();
        var recipient = {{ user.pk }}
        post_url = "{% url 'msg_profile_post_url' %}"
        var message = $('#id_content').val();

        $.ajax({
				url: post_url,
				method: "POST",
				data: {
					"recipient": recipient,
                    "message": message,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
				},
                success: function(data){
                    console.log(data)
                    if (data.status == 'success'){
				            $("#Modal").modal("hide");                            
			            }   
			        else{
                            $("#Modal").modal("hide");
                            alert("sorry your message was not successfully sent \n try again!!");                            
			            } 
                }
        });
			
});

	</script>

    {% endblock javascript %}

accounts/templates/profile_update.html
{% extends 'base.html' %}

{% block headerlinks %}
    <link rel="stylesheet" href="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588534996/static/css/bootstrap-grid.min_dvchja.css">
    <link href="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588534996/static/css/cropper.min_cporwb.css" rel="stylesheet">
    <link href="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588534997/static/css/bootstrap.min_sq8nsp.css" rel="stylesheet">
{% endblock %}

 {% block style %}

body{
    background: white;
}
footer{
    display: none;
}
.profile_section{
    padding-top: 0px;
    margin-top: 100px;
    margin-left: 30px;
    margin-right: 30px;
}
.picture-aside{
    text-align: center;
    background: white;z
}
.profile_pic{
    border-radius: 100%;
    max-width: 70%;
    margin-bottom: 30px;
}
.profile_hr{
    margin-top: 0px;
}
.new_story_form{
    margin-top: 30px;
}
.new_story_input{
    margin-bottom: 10px;
}
.editprofile_btn{
    display: none;
}
 {% endblock %}

{% block content %}

    <section class=" s-content--top-padding s-content--narrow profile_section">
        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-10 picture-aside">
            <div class="">

            </div>
            <img class="profile_pic"
                src="{{ user.userprofile.profile_pic_url }}" alt="">
                <p style="color: rgba(0, 0, 0, 0.5);">@{{ user.username }}</p>

                

            <h1 class="entry__header-title display-1 " 
                style="margin-bottom: 0px; color: slategrey;">
                    {{ user.first_name }} {{ user.last_name }}
            </h1>
                <ul style="color: rgba(0, 0, 0, 0.5); list-style-type:none; float: left;">
                    <li style="float: left;"><span>
                        <i class="fas fa-map-marker-alt"></i>
                        {{ user.userprofile.nationality }}
                    </span></li>
                    <li style="float: left;"><span>
                        <i class="fas fa-at"></i>
                        {{ user.email }}
                    </span></li>
                    <li style="float: left;"><span>
                        <i class="fas fa-phone"></i>
                        {{ user.userprofile.phone_number }}
                    </span></li>
                </ul>
            <div class="editprofile_btn">
            {% if user == request.user %}
                <div class="col-12">
                    <a href="" class="btn btn-sm col" style="float:right;">
                        Edit Profile
                    </a>
                </div>
            {% endif %}
            </div>
        </div>

        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8 picture-aside">
            <form  method='POST' enctype="multipart/form-data" class="new_story_form tab-full end">
            {% csrf_token %}
                <fieldset>

                    <div>
                        <input name="username" id="id_username" class="full-width new_story_input" value="{{ user.username }}" type="text">
                    </div>
                    <div>
                        <input name="first_name" id="id_first_name" class="full-width new_story_input" value="{{ user.first_name }}" type="text">
                    </div>
                    <div>
                        <input name="last_name" id="id_last_name" class="full-width new_story_input" value="{{ user.last_name }}" type="text">
                    </div>
                    <div>
                        <input name="bio" id="id_bio" class="full-width new_story_input" value="{{ user.userprofile.bio }}" type="text">
                    </div>
                    <div>
                        <input name="email" id="id_email" class="full-width new_story_input" value="{{ user.email }}" type="email">
                    </div>
                    <div>
                        <input name="phone_number" id="id_phone_number" class="full-width new_story_input" value="{{ user.userprofile.phone_number }}" type="text">
                    </div>
                    <div>
                        <input name="nationality" id="id_nationality" class="full-width new_story_input" value="{{ user.userprofile.nationality }}" type="text">
                    </div>
                    <div>
                        <input name="profile_pic" id="id_profile_pic" class="full-width new_story_input" type="file">
                    </div>
                    <!--hidden fields to retrieve image croipping properties-->
                    <input type="hidden" name="x" step="any" id="id_x">
                    <input type="hidden" name="y" step="any" id="id_y">
                    <input type="hidden" name="width" step="any" id="id_width">
                    <input type="hidden" name="height" step="any" id="id_height"> 
                    

                    <button type="submit" class="submit btn btn--small">Submit</button>

                </fieldset>

                 <!-- MODAL TO CROP THE IMAGE -->
                <div class="modal fade" id="modalCrop">
                <div class="modal-dialog">
                    <div class="modal-content">
                    <div class="modal-body">
                        <img src="" id="image" style="max-width: 100%;">
                    </div>
                    <div class="modal-footer">
                        <div class="btn-group pull-left" role="group">
                        </div>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-primary js-crop-and-upload">Crop</button>
                    </div>
                    </div>
                </div>
                </div> 

            </form> 
        </div>
    </section> <!-- end s-extra -->



{% endblock content %}

{% block javascript %}
<script>
        $("#id_profile_pic").change(function () {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#image").attr("src", e.target.result);
                    $("#modalCrop").modal("show");
                }
                reader.readAsDataURL(this.files[0]);

                var $image = $("#image");

                var cropBoxData;
                var canvasData;
                $("#modalCrop").on("shown.bs.modal", function () {
                    $image.cropper({
                        viewMode: 1,
                        aspectRatio: 1/1,
                        minCropBoxWidth: 200,
                        minCropBoxHeight: 200,
                        ready: function () {
                        $image.cropper("setCanvasData", canvasData);
                        $image.cropper("setCropBoxData", cropBoxData);
                        }
                    });
                }).on("hidden.bs.modal", function () {
                    cropBoxData = $image.cropper("getCropBoxData");
                    canvasData = $image.cropper("getCanvasData");
                    $image.cropper("destroy");
                    });

                $(".js-crop-and-upload").click(function () {
                    var cropData = $image.cropper("getData");
                    $("#id_x").val(cropData["x"]);
                    $("#id_y").val(cropData["y"]);
                    $("#id_height").val(cropData["height"]);
                    $("#id_width").val(cropData["width"]);
                    //$("#formUpload").submit();
                    $('#modalCrop').modal('hide')
            });
        }
    });
    </script> 
    <script type="text/javascript" src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535125/static/js/bootstrap.min_l4vp3g.js" ></script>
    <script src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535125/static/js/cropper.min_hiyuox.js"></script>
{% endblock %}