PSP/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import admin
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views
from django.conf import settings
from django.conf.urls.static import static


from peoplestory import views



urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r"^AboutUs/$", views.About, name="about"),
    url(r"^ContactUs/$", views.Contact, name="contact"),
    url(r"^PrivacyPolicy/$", views.PrivacyPolicy, name="privacy_policy"),

    path('accounts/', include('accounts.urls')),
    path('Stories/', include('peoplestory.urls')),
    path('DM/', include('directmessages.urls')),
    #authentication urls
    url('^', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

peoplestory/models.py
from django.db import models
from accounts.models import User, UserProfile
from django.utils.html import mark_safe
from markdown import markdown
from django.urls import reverse


#story approval status
APPROVED = 'APPROVED'
NOT_APPROVED = 'NOT_APPROVED'
PENDING = 'PENDING'

APPROVAL_STATUS = [
    (APPROVED, 'approved'),
    (NOT_APPROVED, 'not_approved'),
    (PENDING, 'pending'),
]


class Stories(models.Model):
    full_name = models.CharField(max_length = 255, null=True)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    story_caption = models.CharField(max_length=255)
    story = models.TextField()
    last_updated = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='story_images/', null=True, blank=True)
    image_url = models.CharField(max_length=2000, blank=True, null=True)
    comment_count = models.IntegerField(blank=True, default=0, verbose_name=('comment count'))
    views = models.PositiveIntegerField(default=0)
    likes = models.ManyToManyField(User, blank=True, related_name="story_likes")
    published = models.BooleanField(default=False)
    denied = models.BooleanField(default=False)
    video_link = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return f'story about : { self.full_name }'

    def get_story_as_markdown(self):
        return mark_safe(markdown(self.story, safe_mode='escape'))

    def get_absolute_url(self):
        return reverse("story_detail", kwargs={"pk": self.pk})
    
    class Meta:
        ordering = ['-last_updated']


class Comment(models.Model):
    story = models.ForeignKey(Stories, on_delete = models.CASCADE, related_name="comments")
    comment_author = models.ForeignKey(User, on_delete = models.CASCADE)
    comment_content = models.CharField(max_length = 200,verbose_name = "comment")
    comment_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'by : { self.comment_author }'

    class Meta:
        ordering = ['-comment_date']

peoplestory/forms.py
import datetime
from PIL import Image
from django.core.files import File

from django import forms

from peoplestory.models import Stories, Comment

class NewStoryForm(forms.ModelForm):
    image = forms.ImageField(required=False)
    x = forms.FloatField(required=False)
    y = forms.FloatField(required=False)
    width = forms.FloatField(required=False)
    height = forms.FloatField(required=False)

    class Meta:
        model = Stories
        fields = ['full_name', 'story_caption', 'story', 'image', 'x', 'y', 'width', 'height', 'video_link']


class UpdateStoryForm(forms.ModelForm):
    image = forms.ImageField(required=False)
    x = forms.FloatField(required=False)
    y = forms.FloatField(required=False)
    width = forms.FloatField(required=False)
    height = forms.FloatField(required=False)

    class Meta:
        model = Stories
        fields = ['full_name', 'story_caption', 'story', 'image', 'x', 'y', 'width', 'height', 'video_link']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment_content']

class ContactForm(forms.Form):
    name = forms.CharField(required = True)
    from_email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

templates/about.html
{% extends 'base.html' %}

{% block headerlinks %}
    <link rel="stylesheet" href="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588534997/static/css/bootstrap.min_sq8nsp.css">
    <script src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535126/static/js/jquery-3.1.1.min_fbslvu.js"></script>
    <script src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535125/static/js/bootstrap.min_l4vp3g.js"></script>
{% endblock %}

{% block style %}
.about-title{
    padding-bottom: 0px;
}
.s-content{
    background-color: white;
}
.hr{
    margin-top: 3rem;
    margin-bottom: 3rem;
}
{% endblock %}

{% block content %}


    <!-- s-content
    ================================================== -->
    <section class="s-content s-content--top-padding s-content--narrow" style="padding-top: 80px;">

        <div class="row narrow">
            <div class="col-full s-content__header">
                <h1 class="tracking-in-expand-fwd">About "People Shaping People" </h1>
            </div>
        </div>

        <div class="row">
            <div>
                <p>
                <p class="lead">
                        To build the world, you need nations; to build communities you need people and to build people, you need friends. 
                        Friendship has a huge impact in the well being many people virtually more than anything. Having social connects and interactions
                        improve lives and are even tied to longevity. Friendship transcends the click of a button to ‘add friends’ on a social media network. 
                        Our most powerful connections are the ones we stay in touch with in the real world. 
                </p>
            </div>
            <div class="col-twelve">
            <div class="row">

                <h3 style="margin-top:3rem;">The Book</h3>
                <img class="col-six scale-up-center" src="https://res.cloudinary.com/people-shaping-people941/image/upload/v1616940318/static/Atomen_PSP_COVER_x8_rucjcy.jpg" 
                    
                     sizes="(max-width: 2000px) 100vw, 2000px" alt="" style="padding-left: 0px;padding-bottom: 20px">
                <p>
                To build the world, you need nations; to build communities you need people. The human relationship has a huge impact on the well-being of all people virtually more than anything. Having social contacts and interactions improves lives and even increases longevity. Our most powerful connections are the ones we stay in touch with, in the real world. This book is a captivating, interesting and appealing narrative; it is a memoir that is based on personal reflections of various experiences between the author and many great people, events, and places. The author pulls together over one hundred and twenty (120) real-life untold stories of various personalities amongst us through memories of true-life experiences and insights thereby exploring relationships thoughtfully and engagingly.
                
                </p>
            </div>
                <hr class="hr">

            <div class="row block-1-2 block-tab-full">
                <div class="col-block">
                    <h4 class="quarter-top-margin">The Vision.</h4>
                    <p>
                        To have a generation of people who are positively inspired, mentored and influenced towards personal discovery, 
                        growth and commuity developments through the restoration of personal, 
                        family, and societal values in life's various experiences.
                    </p>    
                    
                    <h4 class="quarter-top-margin">Why "People Shaping People"</h4>
                    <p>To offer you a unique and valuable outlook on friendship, and redefine the true meaning and worth of human relationships.</p>
                </div>
                
                <div class="col-block">
                    <h4 class="quarter-top-margin">The Mission.</h4>
                    <ol>
                        <li>Socially connect thousands of people and positively transform its readers.  </li>
                        <li>Make a great difference by broadening the reader’s perspectives on the positive influence and its benefits in relationships.</li>
                        <li>Connect the past, present and future experiences by passing information, wisdom and knowledge to others. </li>
                        <li>Awaken present and future generations of their spiritual and earthly potentials.</li>
                        <li>Reaffirm the readers’ core values and induce a sense of well-being.</li>
                        <li>Be a legacy of positive accomplishments and reference for generations to come.</li>
                    </ol>
                </div>
                </div>
            </div> <!-- s-content__main -->
        </div> <!-- end row -->
    </div> <!-- s-content__main -->
</div> <!-- end row -->
        <div class="row">
                <h3 style="margin-top:3rem;">Author</h3>
                <img class="col-six scale-up-center" src="https://res.cloudinary.com/people-shaping-people/image/upload/v1580744585/About/about-1000_j5tueb.jpg" 
                    
                     sizes="(max-width: 2000px) 100vw, 2000px" alt="" style="padding-left: 0px;">
                <p>
                Atomen Edom was born in Jos on the 24th of April 1980. He hails from Nasarawa State and is Eggon by tribe. 
                He attended Police Children School in Jos, graduated in 1991 and completed his secondary school education at 
                Government Science School, Kuru in Plateau State in 1997. He obtained a Bachelor of Science degree in 2004 and a 
                Master of Science degree in 2008 in Architecture with MPHIL/PH.D Architecture (in view) from the prestigious 
                University of Jos, Plateau State, Nigeria. 
                
                </p>
        <div>

        <div class="col-12" style="margin-top: 6rem;">
            <h4 class="quarter-top-margin">Image Gallary</h4>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a href="https://res.cloudinary.com/people-shaping-people941/image/upload/v1616941897/static/Screenshot_2021-03-22-11-24-44_dm7qzq.png" class="fancybox" rel="ligthbox">
                <img  src="https://res.cloudinary.com/people-shaping-people941/image/upload/v1616941897/static/Screenshot_2021-03-22-11-24-44_dm7qzq.png" class="zoom img-fluid "  alt="">
            
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a href="https://res.cloudinary.com/people-shaping-people941/image/upload/v1616941900/static/IMG_20180827_153821_nil9so.jpg"  class="fancybox" rel="ligthbox">
                <img  src="https://res.cloudinary.com/people-shaping-people941/image/upload/v1616941900/static/IMG_20180827_153821_nil9so.jpg" class="zoom img-fluid"  alt="">
            </a>
        </div>
        
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a href="https://res.cloudinary.com/people-shaping-people941/image/upload/v1616941897/static/Atomen_PSP_T_shirt_1_wv5gd0.jpg" class="fancybox" rel="ligthbox">
                <img  src="https://res.cloudinary.com/people-shaping-people941/image/upload/v1616941897/static/Atomen_PSP_T_shirt_1_wv5gd0.jpg" class="zoom img-fluid "  alt="">
            </a>
        </div>
        
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a href="https://res.cloudinary.com/people-shaping-people941/image/upload/v1616942277/static/hands-5216585_1920_uyoear.jpg" class="fancybox" rel="ligthbox">
                <img  src="https://res.cloudinary.com/people-shaping-people941/image/upload/v1616942277/static/hands-5216585_1920_uyoear.jpg" class="zoom img-fluid "  alt="">
            </a>
        </div>


            
        

    </section> <!-- end s-content -->


    {% endblock content %}

templates/author_search_results.html
{% extends 'base.html' %}

{% block headerlinks %}
    <link rel="stylesheet" href="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588534997/static/css/bootstrap.min_sq8nsp.css">
{% endblock %}


{% block style %}
.s-content{
    background:white;
    min-height: -webkit-fill-available;
}
.display-1{
    font-size:3rem;
    float: left;
}
.list-group{
    min-width: -webkit-fill-available;
}
.search_div{
    float: right;
}
{% endblock %}


{% block content %}
<section class="s-content">
    <div class="row entries-wrap wide">

        <!-- s-content
    ================================================== -->
    <section class="s-content s-content--top-padding" >

        <div class="row narrow" >
            <div class="col-full s-content__header" data-aos="fade-up" style="padding-left: 0px;">
            {% if searched_result %}
                <span class="display-1 explore-subtitle" style="font-family: monospace;">Search "{{ query }}"</span>
            {% else %}
                <span class="display-1 explore-subtitle" style="font-family: monospace;">Awe.. Sorry no author matched your querry: "{{ query }}"</span>
            {% endif %}

            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 search_div">
        <form role="search" method="get" action="{% url 'author_search_results' %}">
            <input type="text" class="form-control " aria-label="Small" aria-describedby="inputGroup-sizing-sm"
                placeholder="search author's name" name="q"
                style="padding: 0px;
                        padding-left:inherit;
                        height: 3.5rem;
                        background: #251d2d36;
                        border: 1px solid #f2f3f5;
                        border-radius: 7px;">
        </form>

            </div>
            </div>
        </div>
        

        <div class="row entries-wrap add-top-padding wide">
            <div class="entries">


    <div class="list-group">
    {% for user in searched_result %}
        <a href="{% url 'myprofile' user.pk %}" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ user.first_name }} {{ user.last_name }} 
                <span class="badge badge-primary badge-pill">{{ user.stories_set.count }} Stories</span></h5>
                <small class="text-muted">{{user.last_login}}</small>
            </div>
            <p class="mb-1">{{ user.userprofile.truncated_bio }}</p>
            <small class="text-muted"><i class="fa fa-map-marker" aria-hidden="true"></i>{{ user.userprofile.nationality }}</small>
        </a>
    {% endfor %}
    </div>

    <!--pagination-->
    <div class="row pagination-wrap">
        <div class="col-full">
            <nav class="pgn" data-aos="fade-up">

                {% if users.has_other_pages %}
                <ul>
                    {% if users.has_previous %}
                        <li><a class="pgn__prev" href="?page={{ users.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled pgn__prev"><span>&laquo;</span></li>
                    {% endif %}

                    {% for i in users.paginator.page_range %}
                    {% if users.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if users.has_next %}
                    <li><a class="disabled pgn__next" href="?page={{ users.next_page_number }}">&raquo;</a></li>
                    {% else %}
                    <li class="disabled pgn__next"><span>&raquo;</span></li>
                    {% endif %}

                </ul>
                {% endif %}
            </nav>
        </div>
    </div>
<!--end pagination-->

    </section> <!-- end s-content -->

    </div>
</section>

{% endblock content %}

{% block javascript %}

{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block style %}
.contact-title{
    padding-bottom: 0px;
    margin-top: 30px;
}
.contact-input{
    background: #F2F3F5;
}
.s-content{
    background-color: white;
}
input{
    padding:10px;
}
{% endblock %}


{% block content %}


    <!-- s-content
    ================================================== -->
    <section class="s-content s-content--top-padding s-content--narrow">

        <div class="row narrow">
            <div class="col-full s-content__header">
                <h1 class="display-1 display-1--with-line-sep contact-title col-twelve tracking-in-expand-fwd">Contact Us.</h1>

            </div>
        </div>

        <div class="row">
            <div class="col-full s-content__main">

 

                <div class="row">
                    <div class="col-six tab-full">
                        <h4>Where to Find Us</h4>

                        <p>
                         No 57, 11th avenue, federal low-cost Jos, plateau state<br>
                        930 NG
                        </p>

                    </div>

                    <div class="col-six tab-full">
                        <h4>Contact Info</h4>

                        <p>peopleshapingpeople@gmail.com<br>
                        edomatomen@gmail.com <br>
                        Phone: (+234) 7038473653
                        </p>

                    </div>
                </div>

                <h4>Get In Touch</h4>

                <form method="POST">
                {% csrf_token %}
                    <fieldset>

                        <div>
                            <input name="name" id="id_name" class="full-width contact-input" placeholder="your name" value="" type="text">
                        </div>

                        <div class="form-field">
                            <input name="from_email" id="id_from_email" class="full-width contact-input" placeholder="abcd@gmail.com" value="" type="email">
                        </div>

                        <div class="message form-field">
                            <textarea name="message" id="id_message" class="full-width contact-input" placeholder="Your Message"></textarea>
                        </div>

                        <button type="submit" class="submit btn btn--primary btn--large full-width">Send Message</button>

                    </fieldset>
                </form>

            </div> <!-- s-content__main -->
        </div> <!-- end row -->

    </section> <!-- end s-content -->



{% endblock content %}

{%block javascript%}
<script type="text/javascript">
    $(document).ready(function(){
      $('.your-class').slick({
        setting-name: setting-value
      });
    });
  </script>
				
{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}

{% block headerlinks %}
    <link rel="stylesheet" href="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588534996/static/css/bootstrap-grid.min_dvchja.css">
    <link rel="stylesheet" href="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588534996/static/css/card_bqkqqs.css">

    <link rel="stylesheet" href="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588534997/static/css/bootstrap.min_sq8nsp.css">
    <script src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535126/static/js/jquery-3.3.1.slim.min_pufmsv.js"></script>
    <script src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535127/static/js/popper.min_wziygl.js"></script>
    <script src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535125/static/js/bootstrap.min_l4vp3g.js"></script>
{% endblock %}

{% block style %}
.row_entries{
    margin: 0px;
    max-width: -webkit-fill-available;
    padding: 0px;
}
.card_custom{
    padding: 10px;
}
.s-content{
    margin-left: 10px;
    margin-right: 10px;
}
.s-footer{
    display: none;
}
.dashboard-container{
    margin-top: 75px;
    padding: 20px;
    padding-top: 0px;
    
}
.card-body{
    padding: 1.25rem 1.437rem;
}
.card-custom{
    margin-bottom: 20px;
}
.card-title{
    color: #787878;
    margin-bottom: 1.2rem;
    font-size: 1.5rem;
    font-weight: 500;
}
.btn-publish{
    border-color: #47a7f3;
    line-height: 3rem;
    height: 3rem;
    padding-left: 10px;
    padding-right: 10px;
    font-size: x-small;
    color: #a2d3f9;
    font-weight: lighter;
}
.btn-deny{
    border-color: #dc3545;
    line-height: 3rem;
    height: 3rem;
    padding-left: 10px;
    padding-right: 10px;
    font-size: x-small;
    color: #dc3545;
    font-weight: lighter;
}
th{
    font-size: 1.5rem;
}
.pic{
    border-radius: 50%;
    vertical-align: middle;
    margin-top: 10px;
    height: 47px;
    margin-top: 0px;
}
.modal-btn-cancel{
    padding-right: 20px;
    padding-left: 20px;
    border-color: #47a7f3;
    border-radius: 5px;
}
.modal-btn-publish{
    padding-right: 20px;
    padding-left: 20px;
    border-color:#c3f7c5;
    border-radius: 5px;
}
.btn-deactivate{
    border-color: red;
    line-height: 3rem;
    height: 3rem;
    padding-left: 10px;
    padding-right: 10px;
    font-size: x-small;
    color: red;
    font-weight: lighter;
}
{% endblock %}


{% block content %}
<div class="dashboard-container">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 card card_custom" style="padding:10px; background:#f2f2f2;border:none;">

        <div class="card card-custom" style="background: #2196f3d1;">
            <div class="card-body">
            <p class="card-title">Users</p>
            <a href="{% url 'user_dashboard' %}">
                <img src="https://res.cloudinary.com/people-shaping-people/image/upload/v1588535124/static/images/icons/users_ybc1dm.png" >
            </a>

            <span style="float: right;font-size: xx-large;">{{ all_users.count }}<span>
            </span></span>
            </div>
        </div>
        <div class="card card-custom" style="background: #c3f7c5;">
            <div class="card-body">
                <p class="card-title">Published Stories</p>
                <a href="{% url 'published_dashboard' %}">
                    <img src="https://res.cloudinary.com/people-shaping-people/image/upload/v1588535124/static/images/icons/published_q60lvu.png" >
                </a>

                <span style="float: right;font-size: xx-large;" class="published_stories">{{ published_stories.count }}<span>
            </div>
        </div>
        <div class="card card-custom" style="background: #2196f361;">
            <div class="card-body">
                <p class="card-title">Unpublished Stories</p>
                <a href="{% url 'unpublished_dashboard' %}">
                    <img src="https://res.cloudinary.com/people-shaping-people/image/upload/v1588535124/static/images/icons/unpublished_ua5hhx.png" >
                </a>

                <span style="float: right;font-size: xx-large;" class="unpublished_stories">{{ unpublished_stories.count }}<span>
            </div>
        </div>
        <div class="card card-custom" style="background: #ef423545;">
            <div class="card-body">
                <p class="card-title">Denied Stories</p>
                <a href="{% url 'denied_dashboard' %}">
                    <img src="https://res.cloudinary.com/people-shaping-people/image/upload/v1588535120/static/images/icons/denied_ojjdeu.png" >
                </a>

                <span style="float: right;font-size: xx-large;" class="denied_stories">{{ denied_stories.count }}<span>
            </div>
        </div>
            

    </div>

    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12 card card_custom" style="padding:10px; ">

    {% block extended-dashboard %}
    


    {% endblock extended-dashboard %}

        <div class="row"></div>
    </div>
<div>
{% endblock content %}

{% block javascript %}
<script src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535125/static/js/dashboardajax_kyakce.js"></script>

{% endblock javascript %}

templates/denied_dashboard.html
{% extends 'dashboard.html' %}

{% block extended-dashboard %}
    
<h3 style="margin-top: 1.8rem;color: #627c63;font-weight:normal;" class="">Denied Stories</h3>
    <div class="table-responsive">
        <table class="table table-responsive table-responsive-xl " style="display: table;">
        <thead class="thead-inverse">
            <tr>
                <th>Story No</th>
                <th>Name</th>                          
                <th>Author</th>
                <th>Publish</th>
            </tr>
        </thead>
            <tbody>
                {% for story in denied_stories  %}
                <tr class = "row_{{ story.pk }}">
                    <td>{{ story.pk }}</td>
                    <td><a href="{% url 'story_detail' story.pk %}" style="color:#607d8b7d;">{{ story.full_name }}</a></td>
                    <td><a href="{% url 'myprofile' story.author.pk %}" style="color:#607d8b7d;">{{ story.author }}</a></td>
                    
                    <td>
                        <!-- Publish button HTML -->
                        <span class="deny_btn_{{ story.pk}}">
                            <a class="btn btn-publish" role="button" data-toggle="modal" href="#myPublishModal_{{ story.pk }}">Publish</a>
                        </span>
                
                        <!-- Publish Modal HTML -->
                            <div id="myPublishModal_{{ story.pk }}" class="modal fade" tabindex="-1">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-body">
                                            <p class="are_you_sure">Are you sure you want to publish this Story</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-sm modal-btn-cancel" data-dismiss="modal" >
                                                Cancel
                                            </button>
                                            <button type="button" class="btn btn-sm modal-btn-publish publish" id='publish_{{ story.pk }}' data_href="{% url 'publish' story.pk %}" data-dismiss="modal" story_pk="{{ story.pk }}">
                                                Confirm
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table> 
    </div>
        
    {% endblock extended-dashboard %}

templates/top_authors.html
{% extends 'base.html' %}

{% block headerlinks %}
    <link rel="stylesheet" href="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588534997/static/css/bootstrap.min_sq8nsp.css">
{% endblock %}


{% block style %}
@media only screen and (max-width: 400px){
.s-content{
    padding-top: 50px;
}
}
.s-content{
    background:white;
    min-height: -webkit-fill-available;
}
.display-1{
    font-size:3rem;
    float: left;
}
.list-group{
    min-width: -webkit-fill-available;
}
.search_div{
    float: right;
}
{% endblock %}


{% block content %}
<section class="s-content">
    <div class="row entries-wrap wide">

        <!-- s-content
    ================================================== -->
    <section class="s-content s-content--top-padding" >

        <div class="row narrow" >
            <div class="col-full s-content__header" data-aos="fade-up" style="padding-left: 0px;">
                <span class="display-1 explore-subtitle">Popular Authors</span>

            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 search_div">

        <form role="search" method="get" action="{% url 'author_search_results' %}">
            <input type="text" class="form-control " aria-label="Small" aria-describedby="inputGroup-sizing-sm"
                placeholder="search author's name" name="q"
                style="padding: 0px;
                        padding-left:10px;
                        height: 3.5rem;
                        background: #251d2d36;
                        border: 1px solid #f2f3f5;
                        border-radius: 7px;">
        </form>

            </div>
            </div>
        </div>
        

        <div class="row entries-wrap add-top-padding wide">
            <div class="entries">


    <div class="list-group">
    {% for user in users %}
        <a href="{% url 'myprofile' user.pk %}" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ user.first_name }} {{ user.last_name }} 
                <span class="badge badge-primary badge-pill">{{ user.stories_set.count }} Stories</span></h5>
                <small class="text-muted">{{user.last_login}}</small>
            </div>
            <p class="mb-1">{{ user.userprofile.truncated_bio }}</p>
            <small class="text-muted"><i class="fa fa-map-marker" aria-hidden="true"></i>{{ user.userprofile.nationality }}</small>
        </a>
    {% endfor %}
    </div>

    <!--pagination-->
    <div class="row pagination-wrap">
        <div class="col-full">
            <nav class="pgn" data-aos="fade-up">

                {% if users.has_other_pages %}
                <ul>
                    {% if users.has_previous %}
                        <li><a class="pgn__prev" href="?page={{ users.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled pgn__prev"><span>&laquo;</span></li>
                    {% endif %}

                    {% for i in users.paginator.page_range %}
                    {% if users.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if users.has_next %}
                    <li><a class="disabled pgn__next" href="?page={{ users.next_page_number }}">&raquo;</a></li>
                    {% else %}
                    <li class="disabled pgn__next"><span>&raquo;</span></li>
                    {% endif %}

                </ul>
                {% endif %}
            </nav>
        </div>
    </div>
<!--end pagination-->

    </section> <!-- end s-content -->

    </div>
</section>

{% endblock content %}

{% block javascript %}

{% endblock %}