PSP/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import admin
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views
from django.conf import settings
from django.conf.urls.static import static


from peoplestory import views



urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r"^AboutUs/$", views.About, name="about"),
    url(r"^ContactUs/$", views.Contact, name="contact"),
    url(r"^PrivacyPolicy/$", views.PrivacyPolicy, name="privacy_policy"),

    path('accounts/', include('accounts.urls')),
    path('Stories/', include('peoplestory.urls')),
    path('DM/', include('directmessages.urls')),
    #authentication urls
    url('^', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

peoplestory/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import HttpResponse
from django.shortcuts import render
from . import views
from . import dashboard_views


urlpatterns = [
    url(r"^NewStory/$", views.CreateStoryView, name="create_story"),
    url(r"^MyStories/$", views.MyStory, name="my_stories"),
    url(r"^DeleteStory/(?P<pk>\d+)$", views.StoryDeleteView.as_view(), name="story_delete_confirm"),
    url(r"^StoryDetail/(?P<pk>\d+)$", views.StoryDetailView, name="story_detail"),
    url(r"^StoryDetail/(?P<pk>\d+)/EditStory$", views.UpdateStoryView, name="edit_story"),
    url(r"^(?P<pk>\d+)/Story/Like$", views.StoriesLikeToggle, name="like"),
    url(r"^SearchResult/$", views.SearchResultView.as_view(), name="search_results"),
    url(r"^Explore/$", views.ExploreView, name="explore"),
    

    #dashboard urls
    url(r"^Dashboard/Upublished/$", dashboard_views.UnpublishedDashboardView, name="unpublished_dashboard"),
    url(r"^Dashboard/Published/$", dashboard_views.PublishedDashboardView, name="published_dashboard"),
    url(r"^Dashboard/Denied/$", dashboard_views.DeniedDashboardView, name="denied_dashboard"),
    url(r"^Dashboard/User/$", dashboard_views.UserDashboardView, name="user_dashboard"),
    url(r"^Dashboard/User/Publish/(?P<pk>\d+)$", dashboard_views.StoryPublishToggle, name="publish"),
    url(r"^Dashboard/User/Deny/(?P<pk>\d+)$", dashboard_views.StoryDenyToggle, name="deny"),
    url(r"^Dashboard/User/Activate/(?P<pk>\d+)$", dashboard_views.UserDeactivateToggle, name="deactivate"),
    url(r"^Dashboard/User/Deactivate/(?P<pk>\d+)$", dashboard_views.UserActivateToggle, name="activate"),

]

peoplestory/models.py
from django.db import models
from accounts.models import User, UserProfile
from django.utils.html import mark_safe
from markdown import markdown
from django.urls import reverse


#story approval status
APPROVED = 'APPROVED'
NOT_APPROVED = 'NOT_APPROVED'
PENDING = 'PENDING'

APPROVAL_STATUS = [
    (APPROVED, 'approved'),
    (NOT_APPROVED, 'not_approved'),
    (PENDING, 'pending'),
]


class Stories(models.Model):
    full_name = models.CharField(max_length = 255, null=True)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    story_caption = models.CharField(max_length=255)
    story = models.TextField()
    last_updated = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='story_images/', null=True, blank=True)
    image_url = models.CharField(max_length=2000, blank=True, null=True)
    comment_count = models.IntegerField(blank=True, default=0, verbose_name=('comment count'))
    views = models.PositiveIntegerField(default=0)
    likes = models.ManyToManyField(User, blank=True, related_name="story_likes")
    published = models.BooleanField(default=False)
    denied = models.BooleanField(default=False)
    video_link = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return f'story about : { self.full_name }'

    def get_story_as_markdown(self):
        return mark_safe(markdown(self.story, safe_mode='escape'))

    def get_absolute_url(self):
        return reverse("story_detail", kwargs={"pk": self.pk})
    
    class Meta:
        ordering = ['-last_updated']


class Comment(models.Model):
    story = models.ForeignKey(Stories, on_delete = models.CASCADE, related_name="comments")
    comment_author = models.ForeignKey(User, on_delete = models.CASCADE)
    comment_content = models.CharField(max_length = 200,verbose_name = "comment")
    comment_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'by : { self.comment_author }'

    class Meta:
        ordering = ['-comment_date']

peoplestory/forms.py
import datetime
from PIL import Image
from django.core.files import File

from django import forms

from peoplestory.models import Stories, Comment

class NewStoryForm(forms.ModelForm):
    image = forms.ImageField(required=False)
    x = forms.FloatField(required=False)
    y = forms.FloatField(required=False)
    width = forms.FloatField(required=False)
    height = forms.FloatField(required=False)

    class Meta:
        model = Stories
        fields = ['full_name', 'story_caption', 'story', 'image', 'x', 'y', 'width', 'height', 'video_link']


class UpdateStoryForm(forms.ModelForm):
    image = forms.ImageField(required=False)
    x = forms.FloatField(required=False)
    y = forms.FloatField(required=False)
    width = forms.FloatField(required=False)
    height = forms.FloatField(required=False)

    class Meta:
        model = Stories
        fields = ['full_name', 'story_caption', 'story', 'image', 'x', 'y', 'width', 'height', 'video_link']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment_content']

class ContactForm(forms.Form):
    name = forms.CharField(required = True)
    from_email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

peoplestory/views.py
from urllib.parse import quote_plus
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from accounts.models import User
from peoplestory.models import Stories
from django.views.generic import ListView, DeleteView, DetailView, RedirectView
from django.urls import reverse_lazy
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from django.db.models import Q, Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from PIL import Image
from django.core.files import File
from django.core.files.base import ContentFile
from io import BytesIO
import cloudinary

from .forms import NewStoryForm, CommentForm, ContactForm, UpdateStoryForm


def home(request):
    my_stories_query = Stories.objects.filter(published=True).filter(denied=False).order_by('?')
    paginator = Paginator(my_stories_query, 18)
    page = request.GET.get('page', 1)

    try:
        my_stories = paginator.page(page)
    except PageNotAnInteger:
        my_stories = paginator.page(1)
    except EmptyPage:
        my_stories = paginator.page(paginator.num_pages)
  
    context = {
        'my_stories': my_stories,
    }
    return render(request, 'home.html', context)


class SearchResultView(ListView):
    template_name = 'search_results.html'
    context_object_name = 'searched_result'
    paginate_by = 5
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['query'] = self.request.GET.get('q')
        return context

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query is not None:
            or_lookup_stories = (
                Q(full_name__icontains=query) |
                Q(story__icontains=query)
                )
            stories_result = Stories.objects.filter(or_lookup_stories)


            return stories_result
        return Stories.objects.none()      


def About(request):
    return render(request, 'about.html')


def PrivacyPolicy(request):
    return render(request, 'privacypolicy.html')


def Contact(request):
    form = ContactForm(request.POST)

    if request.method == 'POST':          
        if form.is_valid():
            subject = form.cleaned_data['name']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']

            try:
                send_mail(from_email, message, from_email, ['peopleshapingpeople@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')

            messages.success(request, 'Your message has been sent successfully, you would recieve a response very soon!')
  
            return HttpResponseRedirect(request.path_info)
        else:
            messages.warning(request, 'message was Unsuccessfully')

    else:
        form = ContactForm()

    return render(request, 'contact.html', {'form': form})


@login_required
def CreateStoryView(request):  
    form = NewStoryForm(request.POST, request.FILES)
    if request.method == 'POST':
        if form.is_valid():
            story = form.save(commit=False)
            story.author = request.user
            if story.image:
                x = form.cleaned_data.get('x')
                y = form.cleaned_data.get('y')
                width = form.cleaned_data.get('width')
                height = form.cleaned_data.get('height')

                image_obj = Image.open(story.image)
                cropped_image = image_obj.crop((x, y, width+x, height+y))
                resized_image = cropped_image.resize((400, 420), Image.ANTIALIAS)
                thumb_io = BytesIO()
                resized_image.save(thumb_io, image_obj.format)
                
                #save to cloudinary
                try:
                    response = cloudinary.uploader.upload(ContentFile(thumb_io.getvalue()), folder = "story_image")
                    image_url = response['secure_url']  
                except:
                    image_url = "https://res.cloudinary.com/people-shaping-people/image/upload/v1581281253/Default%20Images/fantasies-4063346_640_fbaaqb.jpg"
                    messages.warning(request, 'your image upload failed, you can resolve this by editing your story to add prefered image.')
                
                story.image_url = image_url
                story.image.delete()            
                story.save()
                
                messages.success(request, 'Your story has been successfully created Not it would be reviewed and published Soon')
            else:
                image_url = "https://res.cloudinary.com/people-shaping-people/image/upload/v1581281253/Default%20Images/fantasies-4063346_640_fbaaqb.jpg"
                story.image_url = image_url
                story.save()

            return redirect('my_stories')
        else:
            form = NewStoryForm()
            messages.warning(request, 'Your story creation was Unsucessful') 

    return render(request, 'create_story.html', {'form': form})


@login_required
def UpdateStoryView(request, pk):
    story_instance = Stories.objects.get(pk=pk)  
    form = UpdateStoryForm(request.POST, request.FILES, instance=story_instance)

    if request.method == 'POST':          
        if form.is_valid():
            story = form.save(commit=False)
            story.author = request.user

            if story.image:
                x = form.cleaned_data.get('x')
                y = form.cleaned_data.get('y')
                width = form.cleaned_data.get('width')
                height = form.cleaned_data.get('height')

                image_obj = Image.open(story.image)
                cropped_image = image_obj.crop((x, y, width+x, height+y))
                resized_image = cropped_image.resize((400, 420), Image.ANTIALIAS)
                thumb_io = BytesIO()
                resized_image.save(thumb_io, image_obj.format)
                
                #save to cloudinary
                try:
                    response = cloudinary.uploader.upload(ContentFile(thumb_io.getvalue()), folder = "story_image")
                    image_url = response['secure_url']  
                except:
                    image_url = story_instance.image_url
                    messages.warning(request, 'your image upload failed, you can resolve this by editing your story to add prefered image.')
                
                story.image_url = image_url
                story.image.delete()            
                story.save()
                
                messages.success(request, 'Your story has been successfully created Not it would be reviewed and published Soon')
            else:
                image_url = story_instance.image_url
                story.image_url = image_url
                story.save()


            return redirect('story_detail', pk)
        else:
            form = UpdateStoryForm(instance=story_instance)
            messages.warning(request, 'Your story creation was Not Uncessessful')

    context = {
        'form': form,
        'story': story_instance,
    }

    return render(request, 'edit_story.html', context)


@login_required
def MyStory(request):
    pk = request.user.id
    my_stories_query = Stories.objects.all().filter(author_id=pk)

    paginator = Paginator(my_stories_query, 9)
    page = request.GET.get('page', 1)

    try:
        my_stories = paginator.page(page)
    except PageNotAnInteger:
        my_stories = paginator.page(1)
    except EmptyPage:
        my_stories = paginator.page(paginator.num_pages)

    context = {
        'my_stories': my_stories,
    }

    return render(request, 'my_stories.html', context)

class StoryDeleteView(DeleteView):
    model = Stories
    success_url = reverse_lazy('my_stories')
    template_name = 'story_delete.html'


def StoryDetailView(request, pk):
    story = Stories.objects.get(pk=pk)
    story.views += 1
    story.save()
    form = CommentForm(request.POST)
    share_string = quote_plus(story.story_caption)
    popular_stories = Stories.objects.all().order_by('-views')[:5]

    if form.is_valid():
        comment = form.save(commit=False)
        comment.comment_author = request.user
        comment.story = story
        comment.save()
        return HttpResponseRedirect(request.path_info)
    else:
        form = CommentForm()

    context = {
        'story': story,
        'form': form,
        'share_string': share_string,
        'popular_stories': popular_stories
    }

    return render(request, 'story_detail.html', context)


login_required   
def StoriesLikeToggle(request, pk):
    if request.method == 'GET':
        story_id = request.GET['story_id']
        obj = get_object_or_404(Stories, pk=story_id)
        user = request.user
        if user.is_authenticated:
            if user in obj.likes.all():
                liked = False
                obj.likes.remove(user)
                NewLikes = obj.likes.count()
            else:
                liked = True
                obj.likes.add(user)
                NewLikes = obj.likes.count()
            updated = True
        data = {
            "story_id": story_id,
            "updated": updated,
            "NewLikes": NewLikes,
            "liked": liked
        }
        return JsonResponse(data)

        
def ExploreView(request):
    recent_stories = Stories.objects.filter(published=True).filter(denied=False).order_by('-last_updated')[:9]
    my_stories_query = Stories.objects.filter(published=True).filter(denied=False).order_by('-views')
    paginator = Paginator(my_stories_query, 6)
    page = request.GET.get('page', 1)

    try:
        my_stories = paginator.page(page)
    except PageNotAnInteger:

peoplestory/templates/create_story.html
{% extends 'base.html' %}
{% load cloudinary %}
{% load static %}

{% block headerlinks %}
    <link href="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588534996/static/css/cropper.min_cporwb.css" rel="stylesheet">
    <link href="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588534997/static/css/bootstrap.min_sq8nsp.css" rel="stylesheet">
{% endblock %}

{% block style %}
.new_story_form{
    margin-top: 30px;
}
.new_story_input{
    margin-bottom: 10px;
}

input {
    border: 1px solid #ccc !important;
    padding: 10px;

    :last-child {
        margin-top: 10px
    }
}
{% endblock %}


{% block content %}
<section class="s-content">
    <div class="row entries-wrap wide">


    <form  method='POST' enctype="multipart/form-data" class="new_story_form tab-full end" id="formUpload">
    {% csrf_token %}
        <fieldset>

            <div>
                <input name="full_name" style="background: white;" id="id_full_name" class="full-width new_story_input" placeholder="your Full Name" value="" type="text">
            </div>

            <div class="message form-field">
                <input name="image" id="id_image" class="full-width new_story_input" accept="image/*" type="file">
            </div>

            <!--hidden fields to retrieve image croipping properties-->
            <input type="hidden" name="x" step="any" id="id_x">
            <input type="hidden" name="y" step="any" id="id_y">
            <input type="hidden" name="width" step="any" id="id_width">
            <input type="hidden" name="height" step="any" id="id_height"> 

            <div class="form-field">
                <input name="story_caption" style="background: white;" id="id_story_caption" class="full-width new_story_input" placeholder="a sentence to describe your Story" value="" type="text">
            </div>

            <div class="message form-field">
                <textarea name="story" id="id_story" class="full-width new_story_input tinymce" placeholder="Your Message"></textarea>
            </div>

            <div>
                <input name="video_link" style="background: white; margin-top: 10px;" id="id_full_name" class="full-width new_story_input" placeholder="Enter link to audio / video storr (optional)" value="" type="text">
            </div>

            <button type="submit" class="submit btn btn--large full-width" style="margin-top: 10px;">Create Story</button>

        </fieldset>

            <!-- MODAL TO CROP THE IMAGE -->
            <div class="modal fade" id="modalCrop">
            <div class="modal-dialog">
                <div class="modal-content">
                <div class="modal-body">
                    <img src="" id="image" style="max-width: 100%;">
                </div>
                <div class="modal-footer">
                    <div class="btn-group pull-left" role="group">
                    </div>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary js-crop-and-upload">Crop</button>
                </div>
                </div>
            </div>
            </div> 
    </form> 


    </div>
</section>

{% endblock content %}

{% block javascript %}
    <script>
        $("#id_image").change(function () {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#image").attr("src", e.target.result);
                    $("#modalCrop").modal("show");
                }
                reader.readAsDataURL(this.files[0]);

                var $image = $("#image");

                var cropBoxData;
                var canvasData;
                $("#modalCrop").on("shown.bs.modal", function () {
                    $image.cropper({
                        viewMode: 1,
                        aspectRatio: 1/1,
                        minCropBoxWidth: 200,
                        minCropBoxHeight: 200,
                        ready: function () {
                        $image.cropper("setCanvasData", canvasData);
                        $image.cropper("setCropBoxData", cropBoxData);
                        }
                    });
                }).on("hidden.bs.modal", function () {
                    cropBoxData = $image.cropper("getCropBoxData");
                    canvasData = $image.cropper("getCanvasData");
                    $image.cropper("destroy");
                    });

                $(".js-crop-and-upload").click(function () {
                    var cropData = $image.cropper("getData");
                    $("#id_x").val(cropData["x"]);
                    $("#id_y").val(cropData["y"]);
                    $("#id_height").val(cropData["height"]);
                    $("#id_width").val(cropData["width"]);
                    //$("#formUpload").submit();
                    $('#modalCrop').modal('hide')
            });
        }
    });
    </script> 
    <script src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535126/static/js/jquery-3.2.1.min_k5jhcc.js"></script>
    <script type="text/javascript" src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535125/static/js/bootstrap.min_l4vp3g.js" ></script>

    {% comment %} <script type="text/javascript" src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588543687/static/tinymce/tinymce.min_ci9xrn.js" ></script> {% endcomment %}
    {% comment %} <script type="text/javascript" src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535153/static/tinymce/init_tinymce_aukbnz.js" ></script> {% endcomment %}
    <script type="text/javascript" src="{% static 'tinymce/tinymce.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'tinymce/init-tinymce.js' %}" ></script>

    <script src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535125/static/js/cropper.min_hiyuox.js"></script>
{% endblock %}

peoplestory/templates/edit_story.html
{% extends 'base.html' %}
{% load static %}

{% block headerlinks %}
    <link href="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588534996/static/css/cropper.min_cporwb.css" rel="stylesheet">
    <link href="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588534997/static/css/bootstrap.min_sq8nsp.css" rel="stylesheet">
{% endblock %}

{% block style %}
.new_story_form{
    margin-top: 30px;
}
.new_story_input{
    margin-bottom: 10px;
}
{% endblock %}


{% block content %}
<section class="s-content">
    <div class="row entries-wrap wide">

        <form  method='POST' enctype="multipart/form-data" class="new_story_form col-ten md-ten tab-full end">
        {% csrf_token %}

                <div>
                    <input name="full_name" style="background: white;" id="id_full_name" class="full-width new_story_input" value="{{ story.full_name }}" type="text">
                </div>

                <div class="message form-field">
                    <label><img src="{{ story.image_url }}" style="height: 100px;"/></label>
                    <input name="image" id="id_image" class="full-width new_story_input" accept="image/*" type="file">
                </div>

                <!--hidden fields to retrieve image croipping properties-->
                <input type="hidden" name="x" step="any" id="id_x">
                <input type="hidden" name="y" step="any" id="id_y">
                <input type="hidden" name="width" step="any" id="id_width">
                <input type="hidden" name="height" step="any" id="id_height"> 

                <div class="form-field">
                    <input name="story_caption" style="background: white;" id="id_story_caption" class="full-width new_story_input" value="{{ story.story_caption }}" type="text">
                </div>

                <div class="message form-field">
                    <textarea name="story" id="id_story" class="full-width new_story_input tinymce" >{{ story.get_story_as_markdown}}</textarea>
                </div>

                <div class="form-field">
                    <input name="video_link" style="background: white;" id="id_story_caption" class="full-width new_story_input" value="{{ story.video_link }}" type="text">
                </div>

                <button type="submit" class="submit btn btn--large full-width" style="margin-top: 10px;">Update</button>

        </form>

    </div>

    <!-- MODAL TO CROP THE IMAGE -->
            <div class="modal fade" id="modalCrop">
            <div class="modal-dialog">
                <div class="modal-content">
                <div class="modal-body">
                    <img src="" id="image" style="max-width: 100%;">
                </div>
                <div class="modal-footer">
                    <div class="btn-group pull-left" role="group">
                    </div>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary js-crop-and-upload">Crop</button>
                </div>
                </div>
            </div>
            </div> 
</section>

{% endblock content %}

{% block javascript %}
    <script>
        $("#id_image").change(function () {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#image").attr("src", e.target.result);
                    $("#modalCrop").modal("show");
                }
                reader.readAsDataURL(this.files[0]);

                var $image = $("#image");

                var cropBoxData;
                var canvasData;
                $("#modalCrop").on("shown.bs.modal", function () {
                    $image.cropper({
                        viewMode: 1,
                        aspectRatio: 1/1,
                        minCropBoxWidth: 200,
                        minCropBoxHeight: 200,
                        ready: function () {
                        $image.cropper("setCanvasData", canvasData);
                        $image.cropper("setCropBoxData", cropBoxData);
                        }
                    });
                }).on("hidden.bs.modal", function () {
                    cropBoxData = $image.cropper("getCropBoxData");
                    canvasData = $image.cropper("getCanvasData");
                    $image.cropper("destroy");
                    });

                $(".js-crop-and-upload").click(function () {
                    var cropData = $image.cropper("getData");
                    $("#id_x").val(cropData["x"]);
                    $("#id_y").val(cropData["y"]);
                    $("#id_height").val(cropData["height"]);
                    $("#id_width").val(cropData["width"]);
                    //$("#formUpload").submit();
                    $('#modalCrop').modal('hide')
            });
        }
    });
    </script> 
    <script type="text/javascript" src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535125/static/js/bootstrap.min_l4vp3g.js" ></script>
    <script type="text/javascript" src="{% static 'tinymce/tinymce.min.js' %}" ></script>
    <script type="text/javascript" src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535153/static/tinymce/init-tinymce_gjcaeh.js" ></script>
    <script type="text/javascript" src="https://res.cloudinary.com/people-shaping-people/raw/upload/v1588535125/static/js/cropper.min_hiyuox.js"></script>
{% endblock %}

peoplestory/templates/partial_create_story.html
{% extends 'registration/login.html' %}


{% block content %}

    <form class="login100-form " method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
            <div class="wrap-input100 validate-input m-b-26 form-group" data-validate="username is required">
                <span class="label-input100">Full Name</span>
                <input class="input100 form-control" type="text" name="full_name" id="id_full_name" placeholder="Enter Your Friend's Full name" required>
                <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input m-b-26 form-group">
                <span class="label-input100">Image</span>
                <input class="input100 form-control" type="file" name="first_name" maxlength="30" id="id_image">
                <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input m-b-26 form-group" >
                <span class="label-input100">Story Caption</span>
                <input class="input100 form-control" type="text" name="id_story_caption" maxlength="30" id="id_story_caption" placeholder="Enter one sentence about the story for your readers" required>
                <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input m-b-26 form-group">
                <span class="label-input100">Story</span>
                <input type="text" class="input100 form-control"  name="story" id="id_story" placeholder="start your story" required>
                <span class="focus-input100"></span>
            </div>

            <div class="container-login100-form-btn">
                <button class="login100-form-btn" type="submit">
                    Submit
                </button>
            </div>
    </form>

{% endblock %}

peoplestory/templates/story_delete.html
{% extends 'registration/login.html' %}


{% block style %}
    <style>
        .reset_paragraph{
            padding: 20px;
            color: darkgrey;
        }
        .confirm_btn{
            margin: 20px;
            margin-top: 10px;
            margin-right: 2px;
        }
        .login100-form-title{
            padding-bottom: 30px;
            padding-top: 30px;
        }
    </style>
{% endblock %}


{% block boxtitle %}
    Confirm Delete
{% endblock %}

{% block boxcontent %}
    
    <form  method="post">
        {% csrf_token %}
        <h5 class="reset_paragraph">  Are you sure you want to delete this story?  </h5>

        <button  type="submit" class="confirm_btn btn "style="border: 1px solid red;color: red; margin-top: 20px;">
        Confirm
        </button>
        <a href="{{ view.get_success_url }}" class="btn"
        style="border: 1px solid rgba(3, 168, 124, 1);color: rgba(3, 168, 124, 1);">
        Cancel
        </a>
    </form>

{% endblock %}